name: Autograding Tests
on:
  - push
  - workflow_dispatch
  - repository_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run JUnit tests (AppTest)
        uses: classroom-resources/autograding-io-grader@v1
        id: junit-tests
        with:
          test-name: JUnit Tests
          id: junit-tests
          command: mkdir -p out && javac -encoding UTF-8 -cp lib/junit-platform-console-standalone.jar -d out src/main/java/App.java src/test/java/AppTest.java && java -jar lib/junit-platform-console-standalone.jar --class-path out --scan-class-path
          input: ""
          expected-output: "failures: 0"
          comparison-method: "contains"
          timeout: 120

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          JUNIT-TESTS_RESULTS: "${{ steps.junit-tests.outputs.result }}"
        with:
          runners: junit-tests
